import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isGameStart, setIsGameStart] = useState<boolean>(true);
  const [isDead, setIsDead] = useState<boolean>(false);

  useEffect(() => {
    if (!isGameStart) return;

    //initGame();

    let gameInterval;
    // window.addEventListener("keydown", handleKeyDown);
    // gameIterval
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* game title screen */}
        {!isGameStart && isDead && <div>hi, snack game here</div>}

        <div className={styles.description}></div>
      </main>
    </>
  );
}
